-- Inserción de 200 registros en la tabla movies
INSERT INTO movies (title, director, release_year) VALUES
('The Shawshank Redemption', 'Frank Darabont', 1994),
('The Godfather', 'Francis Ford Coppola', 1972),
('The Godfather: Part II', 'Francis Ford Coppola', 1974),
('The Dark Knight', 'Christopher Nolan', 2008),
('12 Angry Men', 'Sidney Lumet', 1957),
('Schindler_s List', 'Steven Spielberg', 1993),
('The Lord of the Rings: The Return of the King', 'Peter Jackson', 2003),
('Pulp Fiction', 'Quentin Tarantino', 1994),
('The Good, the Bad and the Ugly', 'Sergio Leone', 1966),
('The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 2001),
('Fight Club', 'David Fincher', 1999),
('Forrest Gump', 'Robert Zemeckis', 1994),
('Inception', 'Christopher Nolan', 2010),
('The Lord of the Rings: The Two Towers', 'Peter Jackson', 2002),
('Star Wars: Episode V - The Empire Strikes Back', 'Irvin Kershner', 1980),
('The Matrix', 'Lana Wachowski', 1999),
('Goodfellas', 'Martin Scorsese', 1990),
('One Flew Over the Cuckoo_s Nest', 'Milos Forman', 1975),
('Se7en', 'David Fincher', 1995),
('The Silence of the Lambs', 'Jonathan Demme', 1991),
('City of God', 'Fernando Meirelles', 2002),
('Life Is Beautiful', 'Roberto Benigni', 1997),
('The Usual Suspects', 'Bryan Singer', 1995),
('Spirited Away', 'Hayao Miyazaki', 2001),
('Saving Private Ryan', 'Steven Spielberg', 1998),
('Parasite', 'Bong Joon Ho', 2019),
('The Green Mile', 'Frank Darabont', 1999),
('Interstellar', 'Christopher Nolan', 2014),
('Léon: The Professional', 'Luc Besson', 1994),
('The Departed', 'Martin Scorsese', 2006),
('Whiplash', 'Damien Chazelle', 2014),
('The Prestige', 'Christopher Nolan', 2006),
('The Lion King', 'Roger Allers', 1994),
('Gladiator', 'Ridley Scott', 2000),
('The Intouchables', 'Olivier Nakache', 2011),
('The Pianist', 'Roman Polanski', 2002),
('Back to the Future', 'Robert Zemeckis', 1985),
('The Shining', 'Stanley Kubrick', 1980),
('The Great Dictator', 'Charlie Chaplin', 1940),
('Cinema Paradiso', 'Giuseppe Tornatore', 1988),
('Modern Times', 'Charlie Chaplin', 1936),
('The Lives of Others', 'Florian Henckel von Donnersmarck', 2006),
('A Beautiful Mind', 'Ron Howard', 2001),
('The Dark Knight Rises', 'Christopher Nolan', 2012),
('Amélie', 'Jean-Pierre Jeunet', 2001),
('The Hunt', 'Thomas Vinterberg', 2012),
('Memento', 'Christopher Nolan', 2000),
('The Big Lebowski', 'Joel Coen', 1998),
('Blade Runner 2049', 'Denis Villeneuve', 2017),
('Ratatouille', 'Brad Bird', 2007),
('Her', 'Spike Jonze', 2013),
('Joker', 'Todd Phillips', 2019),
('The Seventh Seal', 'Ingmar Bergman', 1957),
('The Wizard of Oz', 'Victor Fleming', 1939),
('Once Upon a Time in the West', 'Sergio Leone', 1968),
('Casablanca', 'Michael Curtiz', 1942),
('The Bridge on the River Kwai', 'David Lean', 1957),
('Sunset Boulevard', 'Billy Wilder', 1950),
('The Third Man', 'Carol Reed', 1949),
('Lawrence of Arabia', 'David Lean', 1962),
('The Apartment', 'Billy Wilder', 1960),
('North by Northwest', 'Alfred Hitchcock', 1959),
('Vertigo', 'Alfred Hitchcock', 1958),
('The Maltese Falcon', 'John Huston', 1941),
('12 Years a Slave', 'Steve McQueen', 2013),
('Oldboy', 'Park Chan-wook', 2003),
('The Grand Budapest Hotel', 'Wes Anderson', 2014),
('The Hunt for Red October', 'John McTiernan', 1990),
('The Wolf of Wall Street', 'Martin Scorsese', 2013),
('Django Unchained', 'Quentin Tarantino', 2012),
('The Big Short', 'Adam McKay', 2015),
('The Florida Project', 'Sean Baker', 2017),
('La La Land', 'Damien Chazelle', 2016),
('Inside Out', 'Pete Docter', 2015),
('Gravity', 'Alfonso Cuarón', 2013),
('The Revenant', 'Alejandro G. Iñárritu', 2015),
('Moonlight', 'Barry Jenkins', 2016),
('Arrival', 'Denis Villeneuve', 2016),
('A Ghost Story', 'David Lowery', 2017),
('Lady Bird', 'Greta Gerwig', 2017),
('Three Billboards Outside Ebbing, Missouri', 'Martin McDonagh', 2017),
('Call Me by Your Name', 'Luca Guadagnino', 2017),
('The Shape of Water', 'Guillermo del Toro', 2017),
('The Favourite', 'Yorgos Lanthimos', 2018),
('Roma', 'Alfonso Cuarón', 2018),
('Parasite', 'Bong Joon Ho', 2019),
('1917', 'Sam Mendes', 2019),
('Jojo Rabbit', 'Taika Waititi', 2019),
('Once Upon a Time in Hollywood', 'Quentin Tarantino', 2019),
('Soul', 'Pete Docter', 2020),
('Nomadland', 'Chloé Zhao', 2020),
('Minari', 'Lee Isaac Chung', 2020),
('The Power of the Dog', 'Jane Campion', 2021),
('Dune', 'Denis Villeneuve', 2021),
('Licorice Pizza', 'Paul Thomas Anderson', 2021),
('The French Dispatch', 'Wes Anderson', 2021),
('Spider-Man: No Way Home', 'Jon Watts', 2021),
('Everything Everywhere All at Once', 'Daniel Kwan', 2022),
('Top Gun: Maverick', 'Joseph Kosinski', 2022),
('Elvis', 'Baz Luhrmann', 2022),
('The Batman', 'Matt Reeves', 2022),
('Tár', 'Todd Field', 2022),
('The Whale', 'Darren Aronofsky', 2022),
('Oppenheimer', 'Christopher Nolan', 2023),
('Barbie', 'Greta Gerwig', 2023),
('Killers of the Flower Moon', 'Martin Scorsese', 2023),
('Dune: Part Two', 'Denis Villeneuve', 2024),
('The Marvels', 'Nia DaCosta', 2024),
('The Big Lebowski', 'Joel Coen', 1998),
('Inglourious Basterds', 'Quentin Tarantino', 2009),
('The Truman Show', 'Peter Weir', 1998),
('The Social Network', 'David Fincher', 2010),
('Casino Royale', 'Martin Campbell', 2006),
('The Imitation Game', 'Morten Tyldum', 2014),
('The King_s Speech', 'Tom Hooper', 2010),
('The Iron Giant', 'Brad Bird', 1999),
('The Secret Life of Walter Mitty', 'Ben Stiller', 2013),
('The Girl with the Dragon Tattoo', 'David Fincher', 2011),
('The Theory of Everything', 'James Marsh', 2014),
('The Hobbit: An Unexpected Journey', 'Peter Jackson', 2012),
('The Hobbit: The Desolation of Smaug', 'Peter Jackson', 2013),
('The Hobbit: The Battle of the Five Armies', 'Peter Jackson', 2014),
('Skyfall', 'Sam Mendes', 2012),
('The Martian', 'Ridley Scott', 2015),
('Django Unchained', 'Quentin Tarantino', 2012),
('Gravity', 'Alfonso Cuarón', 2013),
('The Lego Movie', 'Phil Lord', 2014),
('Interstellar', 'Christopher Nolan', 2014),
('Mad Max: Fury Road', 'George Miller', 2015),
('La La Land', 'Damien Chazelle', 2016),
('Moonlight', 'Barry Jenkins', 2016),
('The Shape of Water', 'Guillermo del Toro', 2017),
('Spider-Man: Into the Spider-Verse', 'Bob Persichetti', 2018),
('Parasite', 'Bong Joon Ho', 2019),
('Joker', 'Todd Phillips', 2019),
('Jojo Rabbit', 'Taika Waititi', 2019),
('The Farewell', 'Lulu Wang', 2019),
('The Lighthouse', 'Robert Eggers', 2019),
('1917', 'Sam Mendes', 2019),
('Once Upon a Time in Hollywood', 'Quentin Tarantino', 2019),
('Soul', 'Pete Docter', 2020),
('Minari', 'Lee Isaac Chung', 2020),
('Nomadland', 'Chloé Zhao', 2020),
('The Green Knight', 'David Lowery', 2021),
('Dune', 'Denis Villeneuve', 2021),
('The French Dispatch', 'Wes Anderson', 2021),
('No Time to Die', 'Cary Joji Fukunaga', 2021),
('Licorice Pizza', 'Paul Thomas Anderson', 2021),
('The Power of the Dog', 'Jane Campion', 2021),
('Drive My Car', 'Ryusuke Hamaguchi', 2021),
('Spider-Man: No Way Home', 'Jon Watts', 2021),
('The Batman', 'Matt Reeves', 2022),
('Top Gun: Maverick', 'Joseph Kosinski', 2022),
('Elvis', 'Baz Luhrmann', 2022),
('Everything Everywhere All at Once', 'Daniel Kwan', 2022),
('Tár', 'Todd Field', 2022),
('Nope', 'Jordan Peele', 2022),
('The Whale', 'Darren Aronofsky', 2022),
('Avatar: The Way of Water', 'James Cameron', 2022),
('Killers of the Flower Moon', 'Martin Scorsese', 2023),
('Oppenheimer', 'Christopher Nolan', 2023),
('Barbie', 'Greta Gerwig', 2023),
('Dune: Part Two', 'Denis Villeneuve', 2024),
('The Marvels', 'Nia DaCosta', 2024),
('Poor Things', 'Yorgos Lanthimos', 2024),
('Saltburn', 'Emerald Fennell', 2024),
('The Holdovers', 'Alexander Payne', 2024),
('Maestro', 'Bradley Cooper', 2024),
('Killers of the Flower Moon', 'Martin Scorsese', 2023),
('The Invisible Man', 'Leigh Whannell', 2020),
('The Hunt', 'Craig Zobel', 2020),
('The Personal History of David Copperfield', 'Armando Iannucci', 2019),
('A Quiet Place', 'John Krasinski', 2018),
('Ready Player One', 'Steven Spielberg', 2018),
('The Big Sick', 'Michael Showalter', 2017),
('The Lobster', 'Yorgos Lanthimos', 2015),
('The Grand Budapest Hotel', 'Wes Anderson', 2014),
('Her', 'Spike Jonze', 2013),
('The Master', 'Paul Thomas Anderson', 2012),
('Drive', 'Nicolas Winding Refn', 2011),
('The Artist', 'Michel Hazanavicius', 2011),
('The Secret World of Arrietty', 'Hiromasa Yonebayashi', 2010),
('Fantastic Mr. Fox', 'Wes Anderson', 2009),
('The Fall', 'Tarsem Singh', 2006),
('The Fountain', 'Darren Aronofsky', 2006),
('Eternal Sunshine of the Spotless Mind', 'Michel Gondry', 2004),
('Lost in Translation', 'Sofia Coppola', 2003),
('Adaptation', 'Spike Jonze', 2002),
('Amores Perros', 'Alejandro González Iñárritu', 2000),
('The Sixth Sense', 'M. Night Shyamalan', 1999),
('The Truman Show', 'Peter Weir', 1998),
('The Sweet Hereafter', 'Atom Egoyan', 1997),
('Donnie Brasco', 'Mike Newell', 1997),
('L.A. Confidential', 'Curtis Hanson', 1997),
('Heat', 'Michael Mann', 1995),
('The Usual Suspects', 'Bryan Singer', 1995),
('Three Colors: Red', 'Krzysztof Kieślowski', 1994),
('The Piano', 'Jane Campion', 1993),
('Barton Fink', 'Joel Coen', 1991),
('Do the Right Thing', 'Spike Lee', 1989),
('Wings of Desire', 'Wim Wenders', 1987),
('Blue Velvet', 'David Lynch', 1986),
('The Last Emperor', 'Bernardo Bertolucci', 1987),
('My Dinner with Andre', 'Louis Malle', 1981),
('The King of Comedy', 'Martin Scorsese', 1983),
('Stalker', 'Andrei Tarkovsky', 1979),
('The Man Who Fell to Earth', 'Nicolas Roeg', 1976),
('The Holy Mountain', 'Alejandro Jodorowsky', 1973),
('The Exorcist', 'William Friedkin', 1973),
('The Day of the Jackal', 'Fred Zinnemann', 1973),
('The French Connection', 'William Friedkin', 1971),
('The Graduate', 'Mike Nichols', 1967),
('Persona', 'Ingmar Bergman', 1966),
('The Great Escape', 'John Sturges', 1963),
('Lawrence of Arabia', 'David Lean', 1962),
('The Bridge on the River Kwai', 'David Lean', 1957),
('12 Angry Men', 'Sidney Lumet', 1957),
('On the Waterfront', 'Elia Kazan', 1954),
('Roman Holiday', 'William Wyler', 1953);
